site:
  title: IKAN ALM Documentation
  url: https://docs.ikanalm.com
  start_page: user-guide-en::Introduction.adoc
content:
  sources:    
    #---------
    # ALM Reports
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /alm-reports/alm-reports-linux
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /alm-reports/alm-reports-windows 
    #---------
    # ALM User Guide
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /user-guide/user-guide-en   
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /user-guide/user-guide-fr   
    #---------
    # Demo Installation Guide
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /demo-installation-guide/demo-installation-guide-linux-en     
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /demo-installation-guide/demo-installation-guide-linux-fr  
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /demo-installation-guide/demo-installation-guide-windows-en         
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /demo-installation-guide/demo-installation-guide-windows-fr
    #---------
    # Getting Started
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /getting-started/getting-started-en   
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /getting-started/getting-started-fr 
    #---------
    # How to Guides
    #---------    
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.8'
    start_path: /how-to-agentinstall-en       
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.8'
    start_path: /how-to-agentinstall-fr    
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.8'
    start_path: /how-to-tomcatinstall-en   
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.8'
    start_path: /how-to-tomcatinstall-fr  
  - url: https://github.com/ikandev/docs-how-to-phases
    branches: main
    start_path: /how-to-use-and-develop-phases/how-to-use-and-develop-phases-en     
  - url: https://github.com/ikandev/docs-how-to-phases
    branches: main
    start_path: /how-to-use-and-develop-phases/how-to-use-and-develop-phases-fr
  - url: https://github.com/ikandev/docs-how-to-phases
    branches: main
    start_path: /how-to-phase-parameters
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-ui-agentinstall/how-to-ui-agentinstall-en       
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-ui-agentinstall/how-to-ui-agentinstall-fr   
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-jira-integration/how-to-jira-integration-en  
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-jira-integration/how-to-jira-integration-fr 
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-clear-browsercache/how-to-clear-browsercache-en
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-clear-browsercache/how-to-clear-browsercache-fr    
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-github-integration/how-to-github-integration-en     
  - url: https://github.com/ikandev/docs-how-to
    branches: '5.9'
    start_path: /how-to-github-integration/how-to-github-integration-fr       
    #---------
    # Integrations
    #---------    
  - url: https://github.com/ikandev/docs-integrations-sap
    branches: main
    start_path: /sap-installation   
  - url: https://github.com/ikandev/docs-integrations-sap
    branches: main
    start_path: /sap-technical   
  - url: https://github.com/ikandev/docs-integrations-sap
    branches: main
    start_path: /sap-user-guide 
  - url: https://github.com/ikandev/docs-integrations-websphere
    branches: main
    start_path: /websphere-phases-catalog
  - url: https://github.com/ikandev/docs-integrations-zos
    branches: ['1.0', '2.1']
    start_path: /zos-phases-catalog          
    #---------
    # Installation Guide
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /installation-guide/installation-guide-en    
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /installation-guide/installation-guide-fr      
    #---------
    # Technical Sheet
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /technical-sheet/technical-sheet-en   
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /technical-sheet/technical-sheet-fr  
    #---------
    # Data Model
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: '5.8'
    start_path: /data-model  
    #---------
    # What's new
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: ['5.8', '5.9']
    start_path: /whats-new/whats-new-en 
  - url: https://github.com/ikandev/docs-general
    branches: '5.9'
    start_path: /whats-new/whats-new-fr       
    #---------
    # REST API
    #---------    
  - url: https://github.com/ikandev/docs-general
    branches: '5.9'
    start_path: /rest-api                              
ui:   
  bundle:
    url: /home/ubuntu/ikan-documentation-project/docs-ui/build/ui-bundle.zip
    # snapshot should be set in order to fetch the UI bundle on each website generation (OR by using the CLI attribute --fetch option), otherwise it will use the cached version
    snapshot: true
  supplemental_files: ./supplemental_ui       
output:
  destinations:
  - provider: fs
    path: ./sites
runtime:
  #cache_dir: ./cache/antora
  fetch: true
